export const DEBUG_MODE = true //рендерим отладочную информацию
export const SPEED = 180 //скорость полета птички
export const GRAVITY = 1800 //коэффициент гравитации в игровом мире
export const BIRD_FLAP = 550 //с каким ускорением птичка "взлетает"
export const PIPE_SPAWN_MIN_INTERVAL = 1200 //минимальная задержка перед следующей трубой
export const PIPE_SPAWN_MAX_INTERVAL = 3000 //максимальная задержка
export const AVAILABLE_SPACE_BETWEEN_PIPES = 130 //минимальное свободное пространство между трубами (по вертикали)
export const CLOUDS_SHOW_MIN_TIME = 3000 //минимальная задержка перед следующим облаком
export const CLOUDS_SHOW_MAX_TIME = 5000 //максимальная задержка перед следующим облаком
export const MAX_DIFFICULT = 100 //на основе этого коэффициента также вычисляется расстояние между трубами
export const SCENE = '' //идентификатор сцены, где нужно рендерить. В данном случае пусто (по умолчанию рендерит в body)
export const TITLE_TEXT = "FLAPPY BIRD" //Название игры в главном меню
export const HIGHSCORE_TITLE = "HIGHSCORES" //Название игрового меню
export const HIGHSCORE_SUBMIT = "POST SCORE" //Название кнопки в рекордах для сохранения своего рекорда
export const INSTRUCTIONS_TEXT = "TOUCH\nTO\nFLY" //Инструкция в главном меню
export const DEVELOPER_TEXT = "Developer\nEugene Obrezkov\nghaiklor@gmail.com" //Куда ж без копирайтов :)
export const GRAPHIC_TEXT = "Graphic\nDmitry Lezhenko\ndima.lezhenko@gmail.com"
export const LOADING_TEXT = "LOADING..." //Сообщение о загрузке игры
export const WINDOW_WIDTH = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth
export const WINDOW_HEIGHT = window.innerHeight || document.documentElement.clientHeight || document.getElementsByTagName('body')[0].clientHeight;